[package]
name = "mock-collector"
version = "0.1.0"
edition = "2024"

[dependencies]
opentelemetry-appender-tracing = "0.31.1"
opentelemetry-proto = "0.31.0"
opentelemetry_sdk = "0.31.0"
serde_json = "1.0.145"
tracing = "0.1.41"
tracing-opentelemetry = "0.32.0"
